version: "3"
services:
  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
  link-db:
    container_name: db_container
    image: mongo
    ports:
      - "27017:27017"
  api:
    container_name: api_container
    image: # Imagem do Docker Hub 
    ports:
      - "5000:3050"
    depends_on:
      - link-db
      - redis